# Generated by Django 2.2.13 on 2022-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=15)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Institute', models.CharField(max_length=75)),
                ('Highest_Qualification', models.CharField(max_length=75)),
                ('TypeofDegree', models.CharField(max_length=75)),
                ('FieldofInterest', models.CharField(max_length=300)),
                ('Personal_Statement', models.CharField(max_length=500)),
                ('Feedback', models.CharField(max_length=400)),
            ],
        ),
    ]
