# Generated by Django 2.2.13 on 2022-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(default='not available', max_length=50),
        ),
    ]
