# Generated by Django 2.2.13 on 2022-08-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholarships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('University', models.CharField(max_length=30)),
            ],
        ),
    ]
