# Generated by Django 2.2.13 on 2022-08-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='Apply_date',
            field=models.DateField(auto_now=True, verbose_name='Apply Date'),
        ),
    ]
