# Generated by Django 2.2.13 on 2022-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220819_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='phd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('Apply_date', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('University', models.CharField(max_length=30)),
            ],
        ),
    ]
