# Generated by Django 4.0.6 on 2022-10-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_users_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
