# Generated by Django 4.0.6 on 2022-10-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_user_data_delete_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='First_Name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='Last_Name',
            new_name='lname',
        ),
    ]
