# Generated by Django 4.0.6 on 2022-10-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_first_name_user_data_fname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
