# Generated by Django 4.1.2 on 2022-11-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_scholarships_nationality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Apply_date',
            new_name='apply_date',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Eligibility',
            new_name='eligibility',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Image_link',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Scholarship_details',
            new_name='scholarship_details',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='Tution_structure',
            new_name='tution_structure',
        ),
        migrations.RenameField(
            model_name='scholarships',
            old_name='University_name',
            new_name='university_name',
        ),
    ]
