# Generated by Django 4.1.2 on 2022-11-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0014_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('institute', models.CharField(max_length=75)),
                ('highest_Qualification', models.CharField(max_length=75)),
                ('typeofDegree', models.CharField(max_length=75)),
                ('cgpa', models.FloatField()),
                ('field_of_interest', models.CharField(max_length=300)),
                ('personal_statement', models.CharField(max_length=500)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
