# Generated by Django 4.1.2 on 2022-11-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_profile_age_alter_profile_cgpa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='highest_Qualification',
            new_name='highest_qualification',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='typeofDegree',
            new_name='type_of_degree',
        ),
    ]
