# Generated by Django 4.1.2 on 2022-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_highest_qualification_profile_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
