# Generated by Django 4.1.2 on 2022-11-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_profile_type_of_degree_typeofdegree_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='history',
            field=models.ManyToManyField(blank=True, to='app1.history'),
        ),
    ]
