# Generated by Django 4.1.2 on 2022-11-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_scholarships_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scholarships',
            new_name='Scholarship',
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
