# Generated by Django 4.1.2 on 2022-11-05 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_scholarship_apply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
