# Generated by Django 4.1.2 on 2022-11-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_program_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_statement',
        ),
        migrations.CreateModel(
            name='PersonalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
        ),
    ]
