# Generated by Django 4.1.2 on 2022-11-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_history_name_history_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='content',
            new_name='personal_statement',
        ),
    ]
