# Generated by Django 4.1.2 on 2022-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
