# Generated by Django 4.1.2 on 2022-11-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='content',
        ),
    ]
