# Generated by Django 4.1.2 on 2022-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_alter_profile_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
    ]
