# Generated by Django 4.1.1 on 2022-12-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_feedback_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created',)},
        ),
    ]
